name: lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pylint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3.1.3
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run pylint
        run: pipenv run lint

  api-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run lin
        run: npm run lint
  
  app-lin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./melanoma_app
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Run lin
        run: npm run lint
